### ISSUE TITLE
Please bump the release number when re-releasing

### ISSUE THREAD

**Issue by alerque** [aliftype/raqq#17]
I published packages for version 1.00 of this back about 2 weeks ago. Now I've gotten some reports that they don't validate properly and it seems to be because the tag for 1.00 got re-created 4 days ago. In the future allow me to suggest it would be worth a minor version bump any time there are changes in the release (even if not in the font) so that downstream packages and repositories don't get messed up. Thanks :)

**Comment by khaledhosny** [comment]
I was hoping no one would notice :) I knew it was a bad move of course, I just didn’t expect it to be packaged anywhere yet. Anyway, I’m cutting a new release in a moment.

**Comment by khaledhosny** [comment]
https://github.com/aliftype/raqq/releases
